version: '3.8'

services:
  app:
    build: .docker
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - php_docker_networks

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    networks:
      - php_docker_networks
    ports:
      - 8000:80
    depends_on:
      - app

networks:
  php_docker_networks: